### ISSUE TITLE
[Modal] Add the ability to hide the BottomAppBar when no action is provided

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1168]
This is a functionality available on the web so it's safe to have on on our side even on the dialog layout.
Came from our internal [chan](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1718182813917159)

**Comment by soulcramer** [comment]
cc @elisa-hery

**Comment by elisa-hery** [comment]
This bug is fixed ✅  see screenshots here : 

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-android/assets/142396647/493ba820-9213-4ac4-ba45-3892f3d38263" width="200px">
</picture>

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-android/assets/142396647/955a2ef6-0868-4872-b898-0771a2532d12" width="400px">
</picture>


Nevertheless, testing helped us to find another bug : ticket [here](https://github.com/adevinta/spark/issues/2247)
