### ISSUE TITLE
Move SparkIcons to this repo

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#117]
Since we use this in some components we need it before migrating them

**Comment by SimonMarquis** [comment]
On this subject, we currently have

```kotlin
abstract class SparkIcon(@DrawableRes override val drawableId: Int) : IconDrawableRes
```

Is it abstract by design? Do we allow custom SparkIcons implementations to exist outside of this module?
Because at the moment, the autocompletion show this:

![image](https://user-images.githubusercontent.com/1921278/220076447-a9031e71-d2a4-4cd3-b0c6-fb8a9d5785cf.png)

If not, we probably should make it a sealed class (and the subclasses as well.

```kotlin
sealed class SparkIcon constructor(@DrawableRes override val drawableId: Int) : IconDrawableRes
```

This would make it simpler to use IMO:
![image](https://user-images.githubusercontent.com/1921278/220076797-47a273ec-3894-4895-bfdb-33586ddc5eb5.png)

**Comment by soulcramer** [comment]
It makes perfect sense!

I used an abstract class initially like you said to allow verticals to extend `SparkIcon` to use their own Icons on components that require a `SparkIcon` to ease Compose migration but now that we have a real Design System initiative I think we can enforce these icons until the verticals have a "real" need for customization

**Comment by soulcramer** [comment]
I've made a first PR #126 where we can put all of this in it but do we want multi-module support before merging it? wdyt @SimonMarquis ?

**Comment by SimonMarquis** [comment]
You can copy paste the configuration for now. I'm in the process of creating the convention plugins at the moment :)
